SOURCES=\
test_gtest.cpp \
test_logging.cpp \
test_types.cpp \
test_arrays.cpp \
test_ndvector.cpp \
test_math.cpp \
test_units.cpp \
test_strings.cpp \
test_atmosphere.cpp \
test_interpolation_extrapolation.cpp \
test_interpolation.cpp \
test_linearalgebra_densevector.cpp \
test_linearalgebra_densevector_complex.cpp \
test_linearalgebra_sparsevector.cpp \
test_linearalgebra_sparsevector_complex.cpp \
test_linearalgebra_densematrix.cpp \
test_linearalgebra_densematrix_complex.cpp \
test_linearalgebra_banddiagonalmatrix.cpp \
test_linearalgebra_banddiagonalmatrix_complex.cpp \
test_linearalgebra_symmetricmatrix.cpp \
test_linearalgebra_matrix_densematrix_real.cpp \
test_linearalgebra_matrix_densematrix_complex.cpp \
test_linearalgebra_matrix_bdmatrix_complex.cpp \
test_linearalgebra_lu.cpp \
test_linearalgebra_basic_solver.cpp \
test_linearalgebra_basic_tridiagonal_solver.cpp \
test_linearalgebra_basic_band_diagonal_solver.cpp \
test_linearalgebra_solver.cpp 
