#pragma once


#if __has_include( "gsl/gsl_spline.h" )
#  ifndef NCPA_INTERPOLATION_GSL_INTERPOLATION_AVAILABLE
#    define NCPA_INTERPOLATION_GSL_INTERPOLATION_AVAILABLE
#  endif
#  if GSL_MAJOR_VERSION >= 2
#    define NCPA_INTERPOLATION_GSL_STEFFEN_SPLINE_AVAILABLE true
#  else
#    define NCPA_INTERPOLATION_GSL_STEFFEN_SPLINE_AVAILABLE false
#  endif
#  include "NCPA/interpolation/gsl/gsl_interpolators.hpp"
#else
#  ifdef NCPA_INTERPOLATION_GSL_INTERPOLATION_AVAILABLE
#    undef NCPA_INTERPOLATION_GSL_INTERPOLATION_AVAILABLE
#  endif
#  define NCPA_INTERPOLATION_GSL_STEFFEN_SPLINE_AVAILABLE false
#endif
