#pragma once

#include "NCPA/interpolation/defines.hpp"
#include "NCPA/interpolation/types.hpp"
#include "NCPA/interpolation/builders.hpp"
#include "NCPA/interpolation/abstract_spline_1d.hpp"
#include "NCPA/interpolation/abstract_spline_2d.hpp"
#include "NCPA/interpolation/abstract_spline_3d.hpp"
#include "NCPA/interpolation/gsl.hpp"
#include "NCPA/interpolation/lanl.hpp"
#include "NCPA/interpolation/Extrapolator1D.hpp"
#include "NCPA/interpolation/nearest_neighbor_spline_1d.hpp"
#include "NCPA/interpolation/nearest_neighbor_spline_2d.hpp"
#include "NCPA/interpolation/stratified_spline_2d.hpp"
#include "NCPA/interpolation/Interpolator1D.hpp"
#include "NCPA/interpolation/Interpolator2D.hpp"
#include "NCPA/interpolation/Interpolator3D.hpp"