#pragma once

#include "NCPA/defines.hpp"
#include "NCPA/exceptions.hpp"
#include "NCPA/gtest.hpp"
#include "NCPA/arrays.hpp"
#include "NCPA/constants.hpp"
#include "NCPA/interpolation.hpp"
#include "NCPA/linearalgebra.hpp"
#include "NCPA/math.hpp"
#include "NCPA/ndvector.hpp"
#include "NCPA/strings.hpp"
#include "NCPA/types.hpp"
#include "NCPA/units.hpp"
#include "NCPA/approx.hpp"
#include "NCPA/atmosphere.hpp"
#include "NCPA/logging.hpp"